export const listings = [
  {
    id: "listing-1",
    name: "Azure Palms Residences",
    image: "/images/azure-palms.png",
    location: "Palm Oasis District",
    beds: 3,
    bath: 4,
    price: "AED 348,295",
    type: "Rent",
  },
  {
    id: "listing-2",
    name: "Golden Dunes Villas",
    image: "/images/golden-dunes.png",
    location: "Emirates Bay",
    beds: 3,
    bath: 4,
    price: "AED 534,295",
    type: "Buy",
  },
  {
    id: "listing-3",
    name: "Golden Dunes Villas",
    image: "/images/golden-dunes.png",
    location: "Emirates Bay",
    beds: 3,
    bath: 4,
    price: "AED 534,295",
    type: "Buy",
  },
  {
    id: "listing-4",
    name: "Golden Dunes Villas",
    image: "/images/golden-dunes.png",
    location: "Emirates Bay",
    beds: 3,
    bath: 4,
    price: "AED 534,295",
    type: "Buy",
  },
  {
    id: "listing-5",
    name: "Golden Dunes Villas",
    image: "/images/golden-dunes.png",
    location: "Emirates Bay",
    beds: 3,
    bath: 4,
    price: "AED 534,295",
    type: "Buy",
  },
];
